// ================================================================
// NPS DASHBOARD DATA
// auto-generated from kommo_export_leads_2026-03-31.xlsx
// generated: 2026-03-31T19:57:18.446Z
// ================================================================

// ─────────────────────────────────────────────────────────────────
// 9. OVERALL NPS SCORE
// Promoters = score 5 | Passives = score 4 | Detractors = score 1-3
// ─────────────────────────────────────────────────────────────────
export const overallNPSData = {
  npsScore: 65.2,
  totalResponses: 990,
  promoters: 755,
  passives: 125,
  detractors: 110,
  promotersPct: 76.3,
  passivesPct: 12.6,
  detractorsPct: 11.1,
} as const;

// ─────────────────────────────────────────────────────────────────
// 4. MONTHLY TIMELINE
// ─────────────────────────────────────────────────────────────────
export const monthlyTimeline = [
  { month: "Jul/25", count: 1 },
  { month: "Ago/25", count: 40 },
  { month: "Set/25", count: 68 },
  { month: "Out/25", count: 102 },
  { month: "Nov/25", count: 173 },
  { month: "Dez/25", count: 109 },
  { month: "Jan/26", count: 155 },
  { month: "Fev/26", count: 138 },
  { month: "Mar/26", count: 14 },
] as const;

// ─────────────────────────────────────────────────────────────────
// 3. PER-COURSE NPS BREAKDOWN
// avgRating = avg of 1-5 NPS question | avgSubDimensions = avg of 1-5 rated sub-questions
// ─────────────────────────────────────────────────────────────────
export const perCourseNPS: Record<string, {
  totalResponses: number;
  npsScore: number | null;
  promoters: number;
  passives: number;
  detractors: number;
  avgRating: number | null;
  avgSubDimensions: {
    facilidadeInscricao: number | null;
    condicoesLocal: number | null;
    alimentacao: number | null;
    material: number | null;
    conteudo: number | null;
    praticas: number | null;
    cordialidadeInstrutores: number | null;
  };
}> = {
  "ACLS": {
    totalResponses: 581,
    npsScore: 66.1,
    promoters: 447,
    passives: 71,
    detractors: 63,
    avgRating: 4.52,
    avgSubDimensions: {
      facilidadeInscricao: 4.72,
      condicoesLocal: 4.64,
      alimentacao: 4.26,
      material: 4.49,
      conteudo: 4.7,
      praticas: 4.87,
      cordialidadeInstrutores: 4.86,
    },
  },
  "PALS": {
    totalResponses: 160,
    npsScore: 64.4,
    promoters: 122,
    passives: 19,
    detractors: 19,
    avgRating: 4.47,
    avgSubDimensions: {
      facilidadeInscricao: 4.64,
      condicoesLocal: 4.57,
      alimentacao: 4.15,
      material: 4.31,
      conteudo: 4.79,
      praticas: 4.9,
      cordialidadeInstrutores: 4.92,
    },
  },
  "OUTRO": {
    totalResponses: 67,
    npsScore: 65.7,
    promoters: 49,
    passives: 13,
    detractors: 5,
    avgRating: 4.52,
    avgSubDimensions: {
      facilidadeInscricao: 4.73,
      condicoesLocal: 4.69,
      alimentacao: 4.43,
      material: 4.31,
      conteudo: 4.7,
      praticas: 4.72,
      cordialidadeInstrutores: 4.88,
    },
  },
  "APH": {
    totalResponses: 39,
    npsScore: 64.1,
    promoters: 31,
    passives: 2,
    detractors: 6,
    avgRating: 4.49,
    avgSubDimensions: {
      facilidadeInscricao: 4.56,
      condicoesLocal: 4.77,
      alimentacao: 4,
      material: 4.67,
      conteudo: 4.74,
      praticas: 4.79,
      cordialidadeInstrutores: 4.85,
    },
  },
  "PHTLS": {
    totalResponses: 24,
    npsScore: 58.3,
    promoters: 17,
    passives: 4,
    detractors: 3,
    avgRating: 4.42,
    avgSubDimensions: {
      facilidadeInscricao: 4.75,
      condicoesLocal: 4.83,
      alimentacao: 4.33,
      material: 4.71,
      conteudo: 4.71,
      praticas: 4.75,
      cordialidadeInstrutores: 4.79,
    },
  },
  "AMLS": {
    totalResponses: 6,
    npsScore: 66.7,
    promoters: 5,
    passives: 0,
    detractors: 1,
    avgRating: 4.67,
    avgSubDimensions: {
      facilidadeInscricao: 4.33,
      condicoesLocal: 4.33,
      alimentacao: 4,
      material: 4.67,
      conteudo: 4.33,
      praticas: 5,
      cordialidadeInstrutores: 5,
    },
  },
  "ATLS": {
    totalResponses: 5,
    npsScore: 20,
    promoters: 2,
    passives: 2,
    detractors: 1,
    avgRating: 4,
    avgSubDimensions: {
      facilidadeInscricao: 4.6,
      condicoesLocal: 4.6,
      alimentacao: 4.2,
      material: 4.4,
      conteudo: 4.6,
      praticas: 4.8,
      cordialidadeInstrutores: 4.8,
    },
  },
};

// ─────────────────────────────────────────────────────────────────
// 2. TOP 30 WORD FREQUENCY IN IMPROVEMENT COMMENTS
// (stopwords removed; accents normalized for counting)
// ─────────────────────────────────────────────────────────────────
export const wordFrequency = [
  { word: "melhorar", count: 33 },
  { word: "tempo", count: 26 },
  { word: "tudo", count: 24 },
  { word: "instrutores", count: 24 },
  { word: "otimo", count: 23 },
  { word: "excelente", count: 23 },
  { word: "nada", count: 23 },
  { word: "praticas", count: 18 },
  { word: "poderia", count: 16 },
  { word: "pratica", count: 16 },
  { word: "melhor", count: 16 },
  { word: "maior", count: 13 },
  { word: "acho", count: 13 },
  { word: "material", count: 12 },
  { word: "local", count: 11 },
  { word: "dias", count: 11 },
  { word: "alimentacao", count: 11 },
  { word: "sem", count: 10 },
  { word: "deveriam", count: 10 },
  { word: "perfeito", count: 9 },
  { word: "qualidade", count: 9 },
  { word: "alunos", count: 9 },
  { word: "apenas", count: 8 },
  { word: "alguns", count: 8 },
  { word: "didatica", count: 8 },
  { word: "informacoes", count: 8 },
  { word: "momento", count: 7 },
  { word: "melhora", count: 7 },
  { word: "prova", count: 7 },
  { word: "gostei", count: 7 },
] as const;

// ─────────────────────────────────────────────────────────────────
// 7. INSTRUCTOR MENTIONS & AVG SCORES
// (parsed from free-text col 27, format "Name - score")
// ─────────────────────────────────────────────────────────────────
export const instructorMentions = [
  { name: "Denilson", mentions: 109, avgScore: 9.66, totalScores: 101 },
  { name: "Juliana", mentions: 73, avgScore: 9.96, totalScores: 65 },
  { name: "Yara", mentions: 60, avgScore: 9.91, totalScores: 53 },
  { name: "Kitt", mentions: 55, avgScore: 9.74, totalScores: 54 },
  { name: "Rubens", mentions: 43, avgScore: 9.98, totalScores: 43 },
  { name: "Walkyson", mentions: 41, avgScore: 9.75, totalScores: 36 },
  { name: "Viviane", mentions: 35, avgScore: 9.97, totalScores: 29 },
  { name: "Italo", mentions: 31, avgScore: 9.93, totalScores: 30 },
  { name: "Thalya", mentions: 30, avgScore: 9.86, totalScores: 28 },
  { name: "Kit", mentions: 29, avgScore: 9.95, totalScores: 29 },
  { name: "Rayra", mentions: 28, avgScore: 9.69, totalScores: 26 },
  { name: "Brenda", mentions: 20, avgScore: 9.94, totalScores: 18 },
  { name: "Josevaldo", mentions: 20, avgScore: 9.89, totalScores: 19 },
  { name: "Bruna", mentions: 17, avgScore: 10, totalScores: 16 },
  { name: "Lilian", mentions: 13, avgScore: 9.27, totalScores: 11 },
  { name: "Thiago", mentions: 13, avgScore: 10, totalScores: 12 },
  { name: "Poliana", mentions: 12, avgScore: 10, totalScores: 12 },
  { name: "Iara", mentions: 11, avgScore: 10, totalScores: 8 },
  { name: "Thalia", mentions: 11, avgScore: 9.7, totalScores: 10 },
  { name: "Morgana", mentions: 10, avgScore: 9.88, totalScores: 8 },
  { name: "Marcus", mentions: 9, avgScore: 10, totalScores: 9 },
  { name: "Erick", mentions: 9, avgScore: 9.8, totalScores: 5 },
  { name: "Erik", mentions: 8, avgScore: 10, totalScores: 6 },
  { name: "Gabriela", mentions: 7, avgScore: 10, totalScores: 5 },
  { name: "Vivi", mentions: 7, avgScore: 10, totalScores: 7 },
  { name: "Larissa", mentions: 7, avgScore: 10, totalScores: 7 },
  { name: "Nota", mentions: 7, avgScore: 9.29, totalScores: 7 },
  { name: "Dr Kitt", mentions: 6, avgScore: 10, totalScores: 6 },
  { name: "Débora", mentions: 6, avgScore: 10, totalScores: 6 },
  { name: "José Alencar", mentions: 6, avgScore: 10, totalScores: 6 },
  { name: "Ítalo", mentions: 5, avgScore: 10, totalScores: 5 },
  { name: "Marcos", mentions: 5, avgScore: 10, totalScores: 4 },
  { name: "Hagi", mentions: 5, avgScore: 10, totalScores: 5 },
  { name: "Duda", mentions: 5, avgScore: 10, totalScores: 5 },
  { name: "Gabriela Melo", mentions: 4, avgScore: 10, totalScores: 4 },
  { name: "Marcio", mentions: 4, avgScore: 10, totalScores: 4 },
  { name: "Debora", mentions: 4, avgScore: 10, totalScores: 4 },
  { name: "Lilia", mentions: 4, avgScore: 8.25, totalScores: 4 },
  { name: "Tiago", mentions: 4, avgScore: 10, totalScores: 4 },
  { name: "Alencar", mentions: 4, avgScore: 10, totalScores: 3 },
  { name: "Denilson Nota", mentions: 3, avgScore: 9.67, totalScores: 3 },
  { name: "Walkyson Nota", mentions: 3, avgScore: 10, totalScores: 3 },
  { name: "Márcio", mentions: 3, avgScore: 10, totalScores: 3 },
  { name: "Talya", mentions: 3, avgScore: 9.67, totalScores: 3 },
  { name: "Maria Eduarda", mentions: 3, avgScore: 9.67, totalScores: 3 },
  { name: "Rayra Pureza", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Yara Nota", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Brena", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Edilson", mentions: 2, avgScore: 10, totalScores: 1 },
  { name: "Thalya Lobo", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Italo Melo", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Italo Melo Nota", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Kitty", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Dra Yara", mentions: 2, avgScore: 9.5, totalScores: 2 },
  { name: "Heraldo", mentions: 2, avgScore: 9.5, totalScores: 2 },
  { name: "Dra Brenda", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Dr Heraldo", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Todos Nota", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Dr Kit", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Bruno", mentions: 2, avgScore: 10, totalScores: 2 },
  { name: "Morganna", mentions: 2, avgScore: 10, totalScores: 1 },
  { name: "Rayara", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Walkynson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Letícia", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Maira", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Edenilson", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Ítalo Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Kitt Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Juliana Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Kite", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Thalya", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dr Morais", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Enfo Rubens", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutores Solícitos", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Com Paciência", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Professores Excelentes", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Didáticos", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Morais", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Polia A", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Itallo", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Lilian Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutores Walkyson", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Lili", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutores Raul", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Hiage", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Kid", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Irene", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Vitória", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Denylson", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Thalita Lobo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Denílson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Herick", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Ambos", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Yara E Viviane", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Italo São", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Josivaldo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Rayara Ambos", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Prof Rubens", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Felipe", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Ítalo Melo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Ótima Didática", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Muito Paciente", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Walkyson E Rayra Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Kitt Brenda", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Dra Vivi", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutora Brenda", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutor Haroldo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutor Kitt", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Herialdo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Liliam", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Lília", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Raíra", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Walkison Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Eric", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Quiy", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Viviane", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Bruna", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Denilson E Juliana Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Juliana", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dr Denilson", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Juliana Maravilhosa Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Bruna As", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Dra Thalia Nota", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Thalia Lobo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Thalita", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Thalya Lobo", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Professor Rubens", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Professor Kitt", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dr Rubens", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dr Thiago", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Para Todos", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Kit Rolla", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Edmilson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Lílian", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Waltyson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Todos", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Os Dois Merecem", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Kit Rola", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Talia", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Morgana Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "José Alencar Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Talya Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Thalya E Denilson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Thalys", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "José De Alencar", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Instrutores", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "José De", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Wallyson Nota", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Excelente Profissional", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Aprendizado De", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Gabriela Foram", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Cristiano", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Dr Hagi", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Dra Larissa", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Yara Sako", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Walysson", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Erike", mentions: 1, avgScore: 10, totalScores: 1 },
  { name: "Excelente Didática", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Profissionalismo", mentions: 1, avgScore: null, totalScores: 0 },
  { name: "Iara Ou Yara", mentions: 1, avgScore: 9, totalScores: 1 },
  { name: "Eduarda", mentions: 1, avgScore: 10, totalScores: 1 },
] as const;

// ─────────────────────────────────────────────────────────────────
// 8. FUTURE COURSES DESIRED
// ─────────────────────────────────────────────────────────────────
export const futureCoursesDesired = [
  { course: "ATLS", count: 418 },
  { course: "PALS", count: 400 },
  { course: "AMLS - Emergências Clínicas", count: 272 },
  { course: "Via Aérea Difícil - I-VAD", count: 218 },
  { course: "Procedimentos Invasivos na Emergência", count: 193 },
  { course: "PHTLS", count: 179 },
  { course: "Ventilação Mecânica Adulto", count: 164 },
  { course: "Ultrassom na Emergência", count: 162 },
  { course: "ACLS", count: 147 },
  { course: "Salas de Emergência Pediátrica", count: 135 },
  { course: "Prescrição Médica", count: 131 },
  { course: "Habilidades Práticas na UTI", count: 112 },
  { course: "Vias Aéreas e Ventilação Pediátrica", count: 104 },
  { course: "APH", count: 96 },
  { course: "Emergência Pré-hospitalar", count: 77 },
  { course: "Trauma Pediátrico", count: 74 },
  { course: "BLS", count: 64 },
  { course: "NENHUM", count: 43 },
  { course: "EPH", count: 42 },
  { course: "SAVE", count: 39 },
] as const;

// ─────────────────────────────────────────────────────────────────
// 5. TOP 10 POSITIVE COMMENTS (NPS score = 5)
// ─────────────────────────────────────────────────────────────────
export const topPositiveComments: string[] = [
  `Atualizar o e-book para 2025`,
  `Não consegui identificar uma falha que precisa ser corrigida no momento`,
  `Um pouco mais de teoria`,
  `O curso pode ser distribuído em 4 turnos, ao invés dos 3. Assim melhora o tempo para as práticas. Exemplo: a prova teórica seria no quarto turno e as práticas seriam realizadas com mais calma.`,
  `gostei muito de tudo`,
  `gostei muito`,
  `Vocês são ótimos!`,
  `Melhora a estrutura`,
  `Ótimo curso com excelente equipe. Porém alguns manequins estão algo desagrados`,
  `Tudo excelente`,
];

// ─────────────────────────────────────────────────────────────────
// 6. TOP 10 CRITICAL COMMENTS (NPS score 1-3)
// ─────────────────────────────────────────────────────────────────
export const topCriticalComments: string[] = [
  `Tá tudo perfeito`,
  `Melhorar a alimentação`,
  `Somente em relação aos livros.`,
  `Talvez o local`,
  `Dois dias para realizar o curso`,
  `Poderiam dividir os temas em 02 dias de curso.`,
  `Apostila com os slides`,
  `Nenhuma observação`,
  `O conteúdo é mt denso, coisas que são só faladas, no choque por exemplo, poderia ser escrito no quadro.`,
  `Abordar pontos importantes mais devagar`,
];

// ─────────────────────────────────────────────────────────────────
// 1. ALL IMPROVEMENT COMMENTS (373 non-empty entries)
// ─────────────────────────────────────────────────────────────────
export const allImprovementComments: string[] = [
  `Atualizar o e-book para 2025`,
  `O coffee break foi muito ruim. \nSalgados frios e somente massa além disso apenas uma opção de bebida. Terrivel!!!`,
  `Rayra`,
  `O local é muito apertado`,
  `Não consegui identificar uma falha que precisa ser corrigida no momento`,
  `Material físico teórico para o curso.`,
  `As aulas são as mesmas dos vídeos da AHA. Me pareceu superficial.`,
  `Um pouco mais de teoria`,
  `Localização e cofre break`,
  `O curso pode ser distribuído em 4 turnos, ao invés dos 3. Assim melhora o tempo para as práticas. Exemplo: a prova teórica seria no quarto turno e as práticas seriam realizadas com mais calma.`,
  `Tudo ótimo`,
  `Continuem`,
  `gostei muito de tudo`,
  `gostei muito`,
  `Vocês são ótimos!`,
  `Melhora a estrutura`,
  `Gostei bastante da Dra Iara e Dra Viviane`,
  `Excelente o curso`,
  `Ótimo curso com excelente equipe. Porém alguns manequins estão algo desagrados`,
  `Tudo excelente`,
  `O curso é muito denso para ser realizado apenas em 2 dias`,
  `Deveria ser em maior tempo`,
  `Satisfatório`,
  `Redistribuir o curso em mais dias`,
  `Nada`,
  `Duração do curso ser um pouco maior; Entrega do material de referência mais antecipada.`,
  `Voltar as apostilas físicas! Fiquei mto trsite quando soube que era digital e solicitei a um amigo que me fornecesse a dele de cursos antigos…`,
  `Nada`,
  `Curso perfeito`,
  `Nenhum.`,
  `Apenas papel toalha nos banheiros hahah`,
  `aaaaa`,
  `Tudo muito bom, exceto pelas macas que são frágeis e inclusive caiu uma maca.`,
  `As macas caíram durante realização da RCP. Isso atrapalhou na qualidade das compressões, pois pelo receio de novos incidentes, as compressões tiveram de ser adaptadas. Sugiro obtenção de macas com material mais resistente.`,
  `Melhorar equipamento \n\nMelhorar preço do curso. Curso muito caro`,
  `Ofertar mais tempo para práticas.`,
  `Excelente curso !`,
  `Curso ótimo\nMelhorar instrumentos`,
  `O curso é muito bom, poderia aumentar o horário do curso e aumentar a quantidade de bonecos livres para treino`,
  `Maior tempo de prática antes da prova`,
  `Qualidade dos equipamentos`,
  `Excelentes instrutores, didáticas impecáveis.`,
  `Equipamentos`,
  `É lente curso é bem aplicado`,
  `Mais cursos na região de Parnaíba- PI`,
  `Comunicação do atendimento (no WhatsApp) no antes do curso, instrução sobre material, o que deve ser feito`,
  `Padronização dos critérios cobrados na prova prática`,
  `Comunicação entre os instrutores. No primeiro dia tivemos uma orientação de prática, no segundo dia divergiu um pouco`,
  `Ítalo precisa de um pouco mais de cordialidade`,
  `Continuem assim!`,
  `Vídeo aulas mais longas e explicativas no site pré aula`,
  `Otimizar o tempo, dar mais dicas praticas`,
  `Curso muito bom`,
  `Muito bom`,
  `Ter mais tempo para curso`,
  `Atualização do curso`,
  `Tudo perfeito`,
  `Livro físico`,
  `Colocar um DÉA verdadeiro`,
  `Colocar um DÉA verdadeiro`,
  `Trazer atualizações`,
  `Lanche`,
  `Não tenho sugestões`,
  `Não foi possível uma parte da aula que seria a videolaringoscopia, por avaria do aparelho.`,
  `Senti falta da prática do videolaringo - o mesmo não funcionou`,
  `Comprar Videolaringo, o presente estava quebrado… complicado`,
  `Faltou vídeo laringo`,
  `Ao ver são profissionais capacitados e foi observado que estão preparados .`,
  `Mais tempo, pois é muito conteúdo`,
  `Melhorar um pouco a opção de alimentos no coffee break.`,
  `Excelente didática`,
  `Tudo bom`,
  `não tenho pontos a observar sobre`,
  `Começar o curso pontualmente independente do atraso dos outros`,
  `Agilidade didática ; melhor manejo do tempo`,
  `Melhorar o controle do tempo`,
  `Professores excelentes, nada a melhorar`,
  `O espaço realizado para as práticas era pequeno, sugiro um local mais amplo, com mais espaço para simulação dos atendimentos.\n\nO livro enviado pelos Correios estava desatualizado, o ideal seria ter um aditivo com as atualizações. \n\nSenti falta do manuseio do Desfibrilador, especialmente as pás pediátricas. O dispositivo utilizado simula bem, mas já fiz ACLS com o uso do desfibrilador “de verdade” e foi mais enriquecedor do ponto de vista prático.\n\nNo mais, curso excelente, muito bem administrado, instrutores ótimas e super acessíveis.`,
  `Tá tudo perfeito`,
  `Tudo excelente`,
  `Material disponível para treino`,
  `Nada`,
  `Adicionar mais cursos de área pediátrica na emergência`,
  `Melhorar a qualidade do material usado. No primeiro curso, a qualidade era melhor.`,
  `Materiais de uma melhor qualidade (ou mais novos)`,
  `Investimento em estrutura, tendo em vista valor investido`,
  `Manter a cordialidade e a atenção com os alunos`,
  `Apresentar melhor o material e melhorar a qualidade do material`,
  `O curso foi muito bem ministrado e as aulas práticas foram bem executadas e tive um excelente aprendizado.`,
  `Os manequins não são ruins, mas poderiam investir em um mais moderno.`,
  `Mais horas de curso`,
  `Os manequins do bls nao estavam conectando, apenas 1 e alguns equipamentos não estava funcionando corretamente.`,
  `Tudo ok.`,
  `Muito bom do jeito que está`,
  `São ótimos`,
  `Sem pontos de melhora`,
  `Acho que as vezes fica complicado quando a profa Yara joga algumas informações igual metralhadora durante as aulas teóricas kkkkk ela é um amor, entendo que ela quer dar essas informações, mas penso que poderia ser com um pouco mais de calma, primeiro deixando se ambientar ao conhecimento próprio básico do pals, aí depois vai aprofundando devagar algumas coisas`,
  `Em relação ao estacionamento`,
  `Curso de obstetrícia`,
  `Curso excelente`,
  `Apostilas atualizadas Acls 2025.`,
  `Apostilas atualizadas Acls 2025.`,
  `Curso excelente, muito bom, minha sugestão é manter a qualidade dos instrutores, dos materiais e da estrutura física do curso.`,
  `Já é top`,
  `Não tenho sugestões`,
  `O curso é muito bom, explicam bem, muita paciência e cordialidade ..`,
  `Ótimo tudo`,
  `Apesar de a carga horária ser extensa em pouco tempo, tentar equilibrar para que seja menos cansativo`,
  `Otimizar o tempo do treinamento para todos terem direito de treinar como líder`,
  `tudo ótimo`,
  `Melhorar a alimentação`,
  `Melhorar conteúdo de estudo( preferir livros físicos para melhor aderência)`,
  `Sem ressalvas. Curso muito bom`,
  `Sem opiniões no momento`,
  `Sem opiniões no momento`,
  `Satisfeita com o resultado do curso`,
  `Muito bom`,
  `Local do curso`,
  `Somente em relação aos livros.`,
  `Talvez o local`,
  `Dois dias para realizar o curso`,
  `Colocação de estações práticas`,
  `Poderiam dividir os temas em 02 dias de curso.`,
  `Acentos e acomodação na sala de aula`,
  `Apostila com os slides`,
  `Metodologia de ensino ótima, mas são muitossss conteúdos, então seria interessante adicionar alguns como gasometria e dividir os pontos em 2 dias. Excelente curso e o professor foi super gentil!`,
  `Livro do curso. Poderia ser uma apostila mais prática, elaborada pelo instrutor, que demonstra muito conhecimento dos temas ministrados. O curso deveria ser divido em dois dias, é muito denso.`,
  `Um curso de emergência obstétrica`,
  `Apenas a sala`,
  `Muito tempo`,
  `Mais insumos`,
  `Poderia ter maior disponibilidade de fios e tempo para treinamento. No momento da lingua de boa, tivemos 1 fio e o horario foi até 17h, porem na inscriçao dizia que era ate 18h.`,
  `Acho que poderiam disponibilizar maior quantidade de fios de sutura para as práticas, principalmente as que utilizam língua de boi.`,
  `na disponibilização dos materiais, deixar que o estudante tenha total responsabilidade sobre a quantidade de material que irá precisar para a sua capacitação e aprendizado.`,
  `Aumentar a disponibilidade dos materias.`,
  `Acho que foi bem didático, bem prático e adorei a metodologia da professora Larissa!`,
  `Aprimorar as doses e focar um pouco mais em IOT`,
  `Tá ótimo.`,
  `Muito bom o curso!`,
  `Poderia incluir almoço.`,
  `Melhor tempo de intervalo`,
  `Sem necessidade de melhora`,
  `2 monitores não estavam fazendo a monitorização.`,
  `O curso foi muito bom, se fosse pra melhorar deveria ter mais mais tempo de prática.`,
  `Muito bom curso`,
  `Foi tudo ótimo`,
  `Tudi ok`,
  `Mais práticas`,
  `Maior rigor para reprovação`,
  `Nenhuma observação`,
  `Equipe muito boa`,
  `Ótimo curso`,
  `Trazer curso na área de neonatologia com práticas`,
  `Nada`,
  `O conteúdo é mt denso, coisas que são só faladas, no choque por exemplo, poderia ser escrito no quadro.`,
  `Embora do material fisco ( bonecos, aparelhos).`,
  `Viviane.\nMaravilhosa, e didática excelente`,
  `Almoço no curso`,
  `Organização dos horários das turmas em cada estação`,
  `Poderia explicar antes do curso que precisa ter uma boa base de ECG e identificação de arritmias. Não tive dificuldades, mas vi que alguns colegas tiveram.`,
  `Nada a melhorar. Tudo Excelente`,
  `Melhorar a parametrização entre turmas. Instrutores muito bons.`,
  `Ar condicionado mais potente`,
  `Nada`,
  `Os textos da apostila podem ser menos prolixo e mais didáticos`,
  `Só a comunicação pelo whatsapp.`,
  `Acho que manter a Yara e a Débora em mais estações. Acho que dava pra ampliar e colocar os casos de OVACE.`,
  `Curso muito bom e proveitoso. Professoras excelentes e didáticas.`,
  `Ta bom`,
  `Primeira vez que estou fazendo. Não consigo definir o que pode ser melhor. Mas foi de grande aprendizado ! Tudo ótimo.`,
  `Tempo`,
  `Foi muito bom o curso, nada a melhorar`,
  `Muito bom o curso`,
  `Foi maravilhoso`,
  `Didatica`,
  `'- Senti falta de um médico dando o curso pra falar algumas coisas mais técnicas voltadas pra médico, embora o enfermeiro tenha muito conhecimento técnico.\n\nGostaria que tivesse almoço incluso no valor da inscrição, que é muito alto pra não fornecer essa refeição.`,
  `Está ótimo do jeito que está`,
  `No local e alimentação.`,
  `So outro locsl`,
  `Outras opções de curso`,
  `somente o local realizado a prova`,
  `A temperatura das salas`,
  `Acho que as aulas online oferecidas deveriam ser mais aprofundadas, pois são muito curtas`,
  `Juliana 10\nErick 10\nKitty 10`,
  `Tudo perfeito. Gostei muito do curso.`,
  `Entregar a atualização 2025 da AHA.`,
  `Não apressar os alunos, haja vista o tempo decorrido para prova estar sendo seguido.`,
  `Nada a comentar`,
  `Nada`,
  `Oferecer almoço`,
  `Curso perfeito`,
  `Satisfeita com todo o curso.`,
  `Abordar pontos importantes mais devagar`,
  `Acho que poderia melhorar a quantidade de refrigerantes. Além disso, a quantidade de alimento da tarde do sábado foi bem pouco, poderia ter sido um pouco melhor.\n\nMas o resto foi perfeito.`,
  `Melhorar coffeebreak`,
  `Renovação no equipamento utilizado no curso`,
  `Organização da sequência de conteúdos ministrados, seguindo uma sequência e sistematização mais organizada.`,
  `Está ótimo`,
  `Mais tempo de curso`,
  `Deve melhorar a plataforma da NC SAUDE pois as vezes é necessário resetar a senha para entrar, pois não reconhece a senha, um suporte de TI seria interessante. Melhorar a estrutura (local) para um mais amplo e refeições em maior quantidade com maior variação de alimentos`,
  `As vezes as informações no livro ficam muito repetitivas o que deixa extenso e cansativo, além de muitas siglas não tão conhecidas ou que foram mencionadas muito tempo antes na leitura e fica difícil de acompanhar e entender.`,
  `Aumentar a quantidade de comidas, revisão em alguns bonecos\nSugestão: Aplicar o curso em 3 dias para um melhor aprendizado e assimilação do conteúdo.`,
  `Espaço maior, e cadeiras mais confortáveis`,
  `Instrutores maravilhosos. Porém achava que o curso teria uma estrutura maior. A televisão era pequena e a luz prejudicava. As cadeiras ruins. Acho que a clínica não suporta o curso. Os instrutores salvaram o curso, são ótimos e super ensinam.`,
  `Mais práticas e menos aulas`,
  `Curso muito bom`,
  `O curso tem uma didática boa, organizado e os instrutores são bem capacitados e cordiais`,
  `Disponibilizar o crachá`,
  `INSTRUTOR WALKYSON NOTA 10`,
  `Nao precisam melhorar em nada. Gostei muito do curso e do instrutor.`,
  `Lugar melhor\nCurso poderia ser mais dividido em horários , ficou muito denso e corrido`,
  `Local`,
  `Poderia se pensar em distribuir o curso em mais dias`,
  `alimentação`,
  `Danilson \n10`,
  `Alimentação, aula de taquiarritmias`,
  `Juliana é ótima, amei, didática, direta e paciente!`,
  `Dinâmica das aulas teóricas.`,
  `Alimentação e permitir ficar com o crachá`,
  `São otimos e muito didáticos`,
  `Horários dos cursos - mais cedo`,
  `Alimentos, papel no banheiro.`,
  `Papel para enxugar as mãos no banheiro`,
  `Abordar mais as dosagens das medicações`,
  `Melhorar lanche entre os intervalos`,
  `Acredito que todas as pessoas poderiam fazer a avaliação de respiratória/choque no primeiro dia e deixar o segundo dia pros casos de cardio`,
  `Papel para enxugar as maos no banheiro`,
  `Adicionar ao portfólio do curso manejo de iam, ave e ventilação mecânica.`,
  `Melhorar cada vez mais as didáticas`,
  `Ensinar mexer no monitor, colocar eletrodos, falar mais sobre os 5h e 5t`,
  `A equipe da NCS é maravilhosa, acredito que a única dica seria sobre o tempo de curso (porém é padrão do ACLS)`,
  `Uniformizar informações que são passadas por preceptores diferentes.`,
  `Maravilhoso`,
  `O curso já é nota 10`,
  `Ter mais tempo de estações práticas`,
  `Ótimo`,
  `Melhorar a questão das atualizações entre instrutores, para falarem a mesma coisa. Enriquecer na demonstração de marcapasso e manobra vagal e sincronização`,
  `Alimentação`,
  `A questão dos lanches, tem muito o que melhorar`,
  `Amei tudo`,
  `Está ótimo`,
  `Mesmo que não haja um momento apenas para IOT, seria interessante dar oportunidade para cada membro treinar apenas 1x.\nAvaliacao de capnografia em tempo real.`,
  `Nada`,
  `Achei ótimo`,
  `Achei o curso excelente`,
  `Tudo ótimo.`,
  `Mais tempo para a prova`,
  `Achei incrível`,
  `Atualização das aulas da AHA de acordo com a nova diretriz`,
  `Acho que tiveram alguns alunos que erraram na condução do ritmo e erro nu número de ciclos da PCR`,
  `Acredito que possam ser algo mais rigorosos durante avaliação pratica`,
  `Curso excelente!!`,
  `Estacionamento`,
  `Achei bem completo`,
  `Menos videoaulas presenciais, se possível.`,
  `Nada a acrescentar, muito bom`,
  `Ótimo curso`,
  `Atualizar materiais para protocolo AHA 2025`,
  `Acredito que o curso é bom, mas poderia melhorar um pouco na didática do conteúdo teorico`,
  `O curso é muito bem ministrado. Os professores são solícitos para sanar nossas dúvidas e nos ajudam muito.`,
  `Local maior`,
  `Excelente`,
  `Acho que poderiam ter algumas aulas dos instrutores, pois costumam ser mais didaticos que os videos da AHA`,
  `Acho que faltou ser um pouco rigoroso. Vi pessoas que acredito que não estavam preparadas, por falharem em muitos pontos sendo aprovadas.`,
  `Nada`,
  `Acredito que mais aulas expositivas ministrada pelos proprios estrutures e não somente por vídeos da AHA`,
  `Tudo otimo. Parabens aos professores!`,
  `Preço`,
  `A alimentação`,
  `Só manter`,
  `Tudo perfeito`,
  `Curso maravilhoso,super recomendo!`,
  `A questão da alimentação, pois o curso é puxado e a alimentação reduzida.`,
  `Ótimos profissionais`,
  `Só manter, tá tudo de ótima qualidade. Instrutores pacientes, prestativos e didáticos.`,
  `Qualificado, manter o padrão do curso`,
  `Queria mais devagar`,
  `Alimentação nos intervalões`,
  `Todos os grupos deveriam passar por todos os instrutores.`,
  `Deveriam melhorar que todos os grupos deveriam passar por todos os professores e os professores deveriam seguir o mesmo raciocínio`,
  `Melhorar preparação de instrutores, todos os alunos deveriam passar por todos os instrutores, para não ser injusto, tem gente que sai mais bem preparado e outros menos.`,
  `Todo mundo passar com todos os instrutores, pra ser mais justo`,
  `Não achei que foi de bom tom os alunos não passarem todos por todos os instrutores, mesmo que seja algo padronizado, fica meio injusto.`,
  `Sobre o Denilson, gostaríamos que ele tivesse interrompido e corrigido a gente mais vezes durante o sábado na aula de PCR. Assim como o grupo que teve com o dr José, teve essas correções e orientações`,
  `Houveram discrepancia entre os instrutores, nos deixando duvidas em algumas condutas asministradas. Alem disso, o coffe foi insuficiente, na minha vez não tinha mais salgados só café, demonstra falta de organização.`,
  `Melhorar coffee break`,
  `Que todas as equipes passem por todos os instrutores do curso!`,
  `A comunicação com os alunos, em relação a equipe de Fortaleza! Pouco acesso e muita empecilhos para facilitar.`,
  `A estrutura do local. O clima da nossa região é quente é necessário ar condicionado funcionando. E ter um estacionamento confiável`,
  `Todas as turmas deveriam passar por todos os instrutores, especialmente, quando se tem a presença de dr Alencar, que todos querem passar por ele!`,
  `Morgana deveria ser mais rígida nos treinamentos`,
  `Já está dentro do esperado`,
  `Em relação ao tempo e ao conteúdo ministrado, queria aprender mais. De resto foi otimo`,
  `NDA`,
  `O curso é excelente, mas acho que poderia melhorar na questão de focar mais nos fluxogramas para estabelecer um raciocínio medular nos alunos.`,
  `Padronizar o nível dos instrutores`,
  `perfeitos`,
  `Contato com todos os instrutores`,
  `O curso é incrível, de bastante aprendizado para a vida prática.`,
  `É um curso excelente, sem apontamentos de melhora`,
  `Fazer estação de sindrome coronariana aguda e AVC`,
  `Deveria ser fornecido almoço, os banheiros poderiam ter uma estrutura melhor, deveria ter melhor manutenção dos bonecos (ventilação de um não estava detectando), além podermos levar o crachá e termo certificado impresso.`,
  `Tá ótimo`,
  `Não tenho nada a reclamar`,
  `Compra bonecos mais modernos`,
  `Gostei bastante do curso. Preparo adequado.`,
  `Marketing`,
  `Mais prática`,
  `Curso perfeito!`,
  `É necessário um melhor alinhamento em relação ao que fazer nas simulações práticas, porque, existiram alguns ruídos de comunicação em relação ao que um instrutor cobrava em relação ao que o outro cobrava.`,
  `O curso em si está muito bem construído, na minha opinião algumas condutas deveriam ser melhor alinhadas pois na hora das práticas somos cobrados na ótica de que tá avaliando e fica difícil saber. Uma prática fui vedado der fazer de acesso intraosseo, por está aqui como técnico, mesmo estando a 3 meses de me formar como enf, enquanto minha amiga também técnica não foi barrada, achei uma situação um tanto chata por não ter sido uma barreira igual a todos, já que na minha justificativa foi estar aqui como técnico. No mais tudo maravilhoso principalmente as práticas e aulas com a Juliana e Denilson`,
  `Nao tenho queixas negativas, nem opcoes de melhorias. Estou satisfeita.`,
  `Algumas informações dadas por instrutores diferentes são conflitantes, uns instruem uma conduta enquanto outros discordam da mesma conduta (dentro de momentos de aprendizado praticos e teoricos, desconsiderando momentos de conversas informais e trocas de experiência), um alinhamento maior nos detalhes seria importante`,
  `Os instrutores devem entrar em um acordo sobre os detalhes e principalmente os momentos corretos a realizar as condutas. Cada um estava querendo de uma forma diferente o que dificulta o aprendizado`,
  `Independente de qualquer resultado que tive no curso, continuem com essa ambiente acolhedor e que facilita tanto a nossa aprendizagem. Obrigado.`,
  `Nada a acrescentar, ótimos instrutores.`,
  `Pode apresentar conteúdos`,
  `Poderia oferecer prática`,
  `Ofertar material`,
  `Só o lanche que não tem opção de suco, fruta, algo saudável`,
  `Ta otimo`,
  `Está ótimo`,
  `Melhora sobre a parte de ECG e vias aéreas`,
  `Avaliar também durante a prova prática a manobra de compressão.`,
  `Acredito que os pontos de melhoria não se aplicam às instrutoras/curso da NC Saúde, mas sim que seria interessante se o curso tivesse duração de 3 dias, com distribuição dos conteúdos ao longo dos 3 dias, possibilitando discussão um pouco mais aprofundada de cada tema`,
  `Todos os alunos deveriam treinar pcr , com diferentes ritmos.`,
  `Curso denso, fracionar em mais dias devido o cansaço`,
  `Na alimentação`,
  `Nada especificamente`,
  `Pontualidade`,
  `Foi tudo muito bom!`,
  `A gente que tem que continuar melhorando`,
  `Muito bom`,
  `Dar mais tempo pra prática, basicamente um estudante treina apenas uma vez em cada função, o que acaba sendo insuficiente.`,
  `Nada.`,
  `Perfeito demais`,
  `Fazer o curso em um tempo maior`,
  `Execelenre. Já`,
  `Talvez os manequim`,
  `Coffe break e bonecos`,
  `Espaço, cadeira sem braço. \nMaterial pouco manequins`,
  `Nada a melhorar. Curso muito bom.`,
  `Já é meu segundo curso na NC e eu adoro. Tem que fazer em Cuz`,
  `Gostei muito do curso. Nada para mudar`,
  `Melhorar a comida`,
  `O local, as cadeiras não tinham apoio. \nLanche poderia ser melhor`,
  `Sem queixas no momento`,
  `Ter mais assentos na sala de prática`,
  `NDN`,
  `Cadeiras do curso`,
  `O curso já é otimo, nada a mudar`,
  `Organizar melhor o conhecimento nas Bradicardias. As informações foram sendo jogadas aos poucos e o raciocínio não ficou muito sistematizado de princípio. No final, o conhecimento foi repassado.\nTambém acho importante valorizar mais a observação sobre a qualidade das RCP durante a prática.`,
  `Poderia ser realizado mais atividades práticas no primeiro dia. Não deveriam ser realizadas provas sem uma rodada de práticas (7 práticas)`,
  `Excelente.`,
  `Muito bom!`,
  `Tudo ótimo`,
  `Curso maravilhoso!`,
  `Precisa-se de uma filial da NC saúde na região do Cariri no Ceará.`,
  `Se tivesse mais um dia de prática o conhecimento fica mais sedimentado, pois é preciso treinar, treinar sequências.`,
  `Curo excelente`,
  `Excelente \nObservei grande melhoria desde o último curso que realizei com nc saúde em 2023. Melhora da didática e engajamento dos alunos para assimilar o conteúdo.`,
  `Nada a opinar no momento.`,
  `Talvez se programasse o acls com um pouco mais de antecedência`,
  `Adequar a possíveis cenários de equipe reduzidas, como em alguns hospitais do interior.`,
  `Melhorar nervosismo de 1 treinee`,
  `Sem opiniões.`,
  `Excelente curso`,
  `Melhorar o projetor e o lanche`,
  `Nada. Tudo bom.`,
  `Excelente curso`,
  `Muito bom!`,
  `Melhorar logística de informações`,
  `Informações mais claras sobre o pré teste`,
];

